Repository LM-channel-team-project/team6, pull requests merged in 2021-05, with the labels that each got.

#48 feat: 디렉토리 구조 변경 및 RelatedPost Cell Component 추가 (#47)
  client/package-lock.json
  client/package.json
  client/public/favicon.ico
  client/public/logo192.png
  client/public/logo512.png
  client/src/App.tsx
  client/src/assets/image/pro.jpeg
  client/src/components/molecules/RelatedPostsCell/index.tsx
  client/src/components/molecules/RelatedPostsCell/style.ts
  client/src/components/organisms/RelatedPostsBody/style.ts
  client/src/components/organisms/RelatedPostsHeader/index.tsx
  client/src/components/templates/RelatedPosts/style.ts
  client/src/index.tsx
  client/src/pages/Main/index.tsx
  client/src/pages/Main/style.ts
  client/yarn.lock
Labels: 기능, 프론트엔드

#56 feat: 로그인 페이지 생성 및 기본 레이아웃설정, 도지 이미지 삽입 (#55)
  client/src/App.tsx
  client/src/assets/image/doge.png
  client/src/commons/style/GlobalStyle.ts
  client/src/components/templates/LoginTemplate/index.tsx
  client/src/components/templates/LoginTemplate/style.ts
  client/src/pages/Login/index.tsx
  client/src/pages/Login/style.ts
Labels: 기능, 프론트엔드

#59 feat: 로그인 페이지 컴포넌트 설정(#58)
  client/src/App.tsx
  client/src/commons/constants/string.ts
  client/src/components/atoms/BasicText/index.tsx
  client/src/components/atoms/BasicText/style.ts
  client/src/components/atoms/ExternalLink/index.tsx
  client/src/components/atoms/ExternalLink/style.ts
  client/src/components/atoms/InternalLink/index.tsx
  client/src/components/atoms/InternalLink/style.ts
  client/src/components/atoms/LoginTitle/index.tsx
  client/src/components/atoms/LoginTitle/style.ts
  client/src/components/molecules/LoginBody/index.tsx
  client/src/components/molecules/LoginBody/style.ts
  client/src/components/molecules/LoginHeader/index.tsx
  client/src/components/molecules/LoginHeader/style.ts
  client/src/components/organisms/LoginContent/index.tsx
  client/src/components/organisms/LoginContent/style.ts
  client/src/components/templates/LoginTemplate/index.tsx
  client/src/components/templates/LoginTemplate/style.ts
Labels: 기능, 프론트엔드

#61 feat: Card Component 추가(#60)
  client/src/assets/image/avatar.png
  client/src/assets/image/bg.png
  client/src/components/atoms/Category/index.tsx
  client/src/components/atoms/Category/style.ts
  client/src/components/atoms/Img/index.tsx
  client/src/components/atoms/Img/style.ts
  client/src/components/atoms/Text/index.tsx
  client/src/components/atoms/Text/style.ts
  client/src/components/molecules/User/index.tsx
  client/src/components/molecules/User/style.ts
  client/src/components/organisms/Card/index.tsx
  client/src/components/organisms/Card/style.ts
  client/src/components/templates/CardList/index.tsx
  client/src/components/templates/CardList/style.ts
  client/src/pages/Main/index.tsx
Labels: 기능, 프론트엔드

#62 [BE] Feat/issue#53
  server/package.json
  server/src/app.ts
  server/src/controllers/v1/auth.controller.ts
  server/src/controllers/v1/index.ts
  server/src/controllers/v1/post.controller.ts
  server/src/models/entity/User.ts
  server/src/routes/auth.router.ts
  server/src/routes/index.ts
  server/src/services/auth.service.ts
  server/src/utils/errorHandler.ts
  server/tsconfig.json
Labels: 기능, 리팩토링, 백엔드

#68 feat: 이메일 로그인 버튼 추가(#67)
  client/package-lock.json
  client/package.json
  client/src/assets/image/login-user.png
  client/src/commons/constants/string.ts
  client/src/components/atoms/LoginButton/index.tsx
  client/src/components/atoms/LoginButton/style.ts
  client/src/components/atoms/LoginTitle/index.tsx
  client/src/components/molecules/LoginBody/index.tsx
  client/src/components/molecules/LoginBody/style.ts
  client/src/components/organisms/LoginContent/style.ts
  client/src/components/organisms/RelatedPostsHeader/index.tsx
  client/yarn.lock
Labels: 기능, 리팩토링, 프론트엔드

#73 [BE] Feat/issue#63
  server/src/app.ts
  server/src/controllers/v1/post.controller.ts
  server/src/models/entity/Post.ts
  server/src/routes/post.router.ts
  server/src/services/post.service.ts
  server/src/utils/custom.ts
Labels: 기능, 리뷰, 리팩토링, 백엔드

#83 feat: 회원가입 Form 추가 및 POST 요 청, Input 변수명 변경 (#72)
  client/src/commons/constants/string.ts
  client/src/components/atoms/Input/index.tsx
  client/src/components/atoms/SignButton/index.tsx
  client/src/components/molecules/LoginBody/index.tsx
  client/src/components/molecules/SignUpBody/index.tsx
  client/src/components/molecules/SignUpFormBody/index.tsx
  client/src/components/molecules/SignUpFormBody/style.ts
  client/src/components/organisms/SignContent/index.tsx
Labels: 기능, 프론트엔드

#85 feat: Add Detail Component 및 Card Component 구조 변경
  client/src/App.tsx
  client/src/assets/image/detail-img.png
  client/src/assets/image/detail-pro.png
  client/src/components/atoms/Img/index.tsx
  client/src/components/atoms/Img/style.ts
  client/src/components/atoms/Text/index.tsx
  client/src/components/atoms/Text/style.ts
  client/src/components/molecules/Like/index.tsx
  client/src/components/molecules/Like/style.ts
  client/src/components/molecules/User/index.tsx
  client/src/components/molecules/User/style.ts
  client/src/components/organisms/PostDetailsBody/index.tsx
  client/src/components/organisms/PostDetailsBody/style.ts
  client/src/components/organisms/PostDetailsHeader/index.tsx
  client/src/components/organisms/PostDetailsHeader/style.ts
  client/src/components/templates/CardList/style.ts
  client/src/components/templates/PostDetails/index.tsx
  client/src/components/templates/PostDetails/style.ts
  client/src/pages/Detail/index.tsx
  client/src/pages/Detail/style.ts
Labels: 기능, 프론트엔드

#86 feat: 회원가입 폼 유효성 검사 추가(#82)
  client/src/App.tsx
  client/src/commons/style/GlobalStyle.ts
  client/src/components/atoms/SignButton/style.ts
  client/src/components/molecules/SignUpFormBody/index.tsx
  client/src/utils/signUpValidateInput/index.ts
Labels: 기능, 리팩토링, 프론트엔드

#93 feat: 개선된 헤더 구현 #91
  client/src/assets/image/dogeright.png
  client/src/components/atoms/DropDown/index.tsx
  client/src/components/atoms/DropDown/style.ts
  client/src/components/atoms/HamburgerMenu/index.tsx
  client/src/components/atoms/HamburgerMenu/style.ts
  client/src/components/atoms/HeaderText/index.tsx
  client/src/components/atoms/HeaderText/style.ts
  client/src/components/atoms/Logo/index.tsx
  client/src/components/atoms/Logo/style.ts
  client/src/components/atoms/SearchBar/index.tsx
  client/src/components/atoms/SearchBar/style.ts
  client/src/components/atoms/TextLink/index.tsx
  client/src/components/atoms/TextLink/style.ts
  client/src/components/molecules/HeaderNavLink/index.tsx
  client/src/components/molecules/HeaderNavLink/style.ts
  client/src/components/organisms/HeaderElements/index.tsx
  client/src/components/organisms/HeaderElements/style.ts
  client/src/components/templates/MainHeader/index.tsx
  client/src/components/templates/MainHeader/style.ts
Labels: 기능, 프론트엔드

#95 feat: dropdown style 수정 및 warning message 해결 #94
  client/src/components/atoms/DropDown/style.ts
  client/src/components/atoms/HamburgerMenu/index.tsx
  client/src/components/atoms/HamburgerMenu/style.ts
Labels: 기능, 버그 수정, 프론트엔드

#97 Detail modified
  client/src/assets/image/detail-pro.png
  client/src/components/atoms/Category/index.tsx
  client/src/components/atoms/Category/style.ts
  client/src/components/atoms/Like/index.tsx
  client/src/components/atoms/Like/style.ts
  client/src/components/molecules/Like/index.tsx
  client/src/components/molecules/Like/style.ts
  client/src/components/molecules/User/index.tsx
  client/src/components/molecules/User/style.ts
  client/src/components/organisms/Card/index.tsx
  client/src/components/organisms/Card/style.ts
  client/src/components/organisms/PostDetailsBody/index.tsx
  client/src/components/organisms/PostDetailsBody/style.ts
  client/src/components/organisms/PostDetailsHeader/style.ts
  client/src/components/templates/CardList/index.tsx
  client/src/components/templates/CardList/style.ts
  client/src/pages/Main/index.tsx
Labels: 프론트엔드

#99 fix: header error in Detail Page #98
  client/src/assets/image/dogeright.png
  client/src/components/atoms/DropDown/style.ts
Labels: 버그 수정, 프론트엔드
