Repository LM-channel-team-project/team6, pull requests merged in 2021-06, with the labels that each got.

#100 feat: 로컬(이메일) 로그인 페이지 생성 (#88)
  client/src/App.tsx
  client/src/commons/constants/string.ts
  client/src/components/atoms/LoginTitle/index.tsx
  client/src/components/atoms/LoginTitle/style.ts
  client/src/components/atoms/SignButton/index.tsx
  client/src/components/molecules/LoginBody/index.tsx
  client/src/components/molecules/LoginEmailBody/index.tsx
  client/src/components/molecules/LoginEmailBody/style.ts
  client/src/components/molecules/LoginEmailHeader/index.tsx
  client/src/components/molecules/LoginEmailHeader/style.ts
  client/src/components/molecules/LoginHeader/index.tsx
  client/src/components/molecules/SignUpBody/index.tsx
  client/src/components/molecules/SignUpBody/style.ts
  client/src/components/molecules/SignUpHeader/index.tsx
  client/src/components/organisms/SignContent/index.tsx
  client/src/pages/LoginEmail/index.tsx
  client/src/pages/LoginEmail/style.ts
  client/src/utils/loginEmailValidateInput/index.tsx
Labels: 기능, 프론트엔드

#106 refactor: 이메일 로그인 텍스트 수정 및 로그인 페이지 푸쉬 (#105)
  client/src/commons/constants/string.ts
  client/src/components/molecules/SignUpBody/index.tsx
Labels: 리팩토링, 프론트엔드

#112 fix: 로그인 라우팅 수정(#111)
  client/src/App.tsx
  client/src/commons/constants/string.ts
  client/src/components/molecules/LoginEmailBody/index.tsx
  client/src/components/organisms/LoginEmailOrg/index.tsx
  client/src/components/organisms/LoginEmailOrg/style.ts
  client/src/components/organisms/LoginOrg/index.tsx
  client/src/components/organisms/LoginOrg/style.ts
  client/src/components/organisms/SignContent/index.tsx
  client/src/components/organisms/SignUpOrg/index.tsx
  client/src/components/organisms/SignUpOrg/style.ts
  client/src/components/templates/SignTemplate/index.tsx
  client/src/components/templates/SignTemplate/style.ts
  client/src/pages/Login/index.tsx
  client/src/pages/LoginEmail/index.tsx
  client/src/pages/SignUp/index.tsx
Labels: 버그, 프론트엔드

#114 feat: Carousel 구현
  client/src/assets/image/arrow.png
  client/src/assets/image/slide1.png
  client/src/components/organisms/Carousel/index.tsx
  client/src/components/organisms/Carousel/style.ts
  client/src/components/organisms/PostDetailsHeader/style.ts
  client/src/pages/Main/index.tsx
Labels: 기능, 프론트엔드
