Repository LM-channel-team-project/team6, pull requests merged in 2021-04, with the labels that each got.

#5 feat: 임현우 테스트
  client/src/App.tsx
Labels: 테스트

#8 change prettier - PR 테스트
  client/.prettierrc
Labels: 테스트, 프론트엔드

#15 [BE] 유저 / 포스트 기능 추가
  .gitignore
  server/.env.sample
  server/.prettierrc
  server/ormconfig.js
  server/ormconfig.json
  server/package.json
  server/src/app.ts
  server/src/bulk-data/comment.json
  server/src/bulk-data/post.json
  server/src/bulk-data/user.json
  server/src/controller/authController.ts
  server/src/controller/postController.ts
  server/src/entity/Comment.ts
  server/src/entity/HashTag.ts
  server/src/entity/Post.ts
  server/src/entity/User.ts
  server/src/module/customError.ts
  server/src/module/customMessage.ts
  server/src/module/customStatus.ts
  server/src/module/index.ts
  server/src/module/jsonResponse.ts
  server/src/route/authRouter.ts
  server/src/route/index.ts
  server/src/route/postRouter.ts
  server/tsconfig.json
  server/yarn.lock
Labels: 기능, 리뷰, 백엔드, 버그 수정

#17 test: PR test #16
  client/src/App.tsx
Labels: 테스트

#18 test: revert PR test
  client/src/App.tsx
Labels: 테스트

#24 feat: CSS 리셋과 글로벌 테마 정의 (#22)
  client/src/App.css
  client/src/App.test.tsx
  client/src/App.tsx
  client/src/index.css
  client/src/index.tsx
  client/src/logo.svg
  client/src/reportWebVitals.ts
  client/src/setupTests.ts
  client/src/style/GlobalStyle.ts
  client/src/style/theme.ts
Labels: 기능, 프론트엔드

#26 Feat/be jest
  .gitignore
  server/.env.sample
  server/package-lock.json
  server/package.json
  server/src/app.ts
  server/src/controller/authController.ts
  server/src/controller/postController.ts
  server/src/entity/User.ts
  server/src/middleware/authenticate.ts
  server/src/route/postRouter.ts
  server/src/test/test.txt
  server/src/util/customError.ts
  server/src/util/customMessage.ts
  server/src/util/customStatus.ts
  server/src/util/index.ts
  server/src/util/jsonResponse.ts
  server/yarn.lock
Labels: 기능, 백엔드, 스타일

#27 Feat/issue#21
  server/.env.sample
  server/package.json
  server/src/app.ts
  server/src/controller/authController.ts
  server/src/controller/index.ts
  server/src/entity/User.ts
  server/src/middleware/authenticate.ts
  server/src/route/authRouter.ts
  server/src/util/passport.config.ts
  server/src/util/strategy/githubStrategy.ts
  server/src/util/strategy/kakaoStrategy.ts
  server/src/util/strategy/localStrategy.ts
  server/yarn.lock
Labels: 기능, 리뷰, 백엔드

#28 [FE] 임포트 절대경로 변경
  client/src/index.tsx
  client/tsconfig.json
Labels: 프론트엔드, 환경 설정

#32 feat: 글로벌 백그라운드 컬러 추가(#30)
  client/src/style/GlobalStyle.ts
Labels: 프론트엔드

#37 [BE] Feat/issue#33
  server/ormconfig.js
  server/package-lock.json
  server/package.json
  server/src/app.ts
  server/src/controllers/v1/auth.controller.ts
  server/src/controllers/v1/post.controller.ts
  server/src/middlewares/authenticate.ts
  server/src/routes/auth.router.ts
  server/src/routes/post.router.ts
  server/src/utils/custom.ts
  server/src/utils/customError.ts
  server/src/utils/customStatus.ts
  server/src/utils/errorHandler.ts
  server/src/utils/index.ts
  server/src/utils/jsonResponse.ts
  server/src/utils/passport.config.ts
  server/src/utils/strategy/github.strategy.ts
  server/src/utils/strategy/kakao.strategy.ts
  server/src/utils/strategy/local.strategy.ts
  server/src/utils/swagger/paths/v1/auth/auth-id.yaml
  server/src/utils/swagger/paths/v1/auth/auth-logout.yaml
  server/src/utils/swagger/paths/v1/auth/auth-signup.yaml
  server/src/utils/swagger/paths/v1/auth/auth.yaml
  server/src/utils/swagger/paths/v1/auth/oauth-github.yaml
  server/src/utils/swagger/paths/v1/auth/oauth-kakao.yaml
  server/src/utils/swagger/paths/v1/index.yaml
  server/src/utils/swagger/swagger.yaml
  server/tsconfig.json
  server/yarn.lock
Labels: 기능, 리뷰, 백엔드, 환경 설정

#39 feat: RelatedPostsLayout 생성 및 글로벌 스타일 수정(#38)
  client/.eslintrc.js
  client/src/index.tsx
  client/src/layout/RelatedPosts/index.tsx
  client/src/layout/RelatedPosts/style.ts
  client/src/style/GlobalStyle.ts
Labels: 기능, 프론트엔드

#41 feat: RelatedPostsHeader / Body 생성(#40)
  client/src/layout/RelatedPosts/index.tsx
  client/src/layout/RelatedPostsBody/index.tsx
  client/src/layout/RelatedPostsBody/style.ts
  client/src/layout/RelatedPostsHeader/index.tsx
  client/src/layout/RelatedPostsHeader/style.ts
Labels: 기능, 프론트엔드

#43 feat: RelatedPostsHeader Components 추가(#42)
  client/src/App.tsx
  client/src/components/Button/index.tsx
  client/src/components/Button/style.ts
  client/src/layout/RelatedPostsHeader/index.tsx
  client/src/layout/RelatedPostsHeader/style.ts
Labels: 기능, 프론트엔드
